[package]
name = "platter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive"] }
colabrodo_server = { git = 'https://github.com/InsightCenterNoodles/colabrodo', branch = "develop" }
colabrodo_common = { git = 'https://github.com/InsightCenterNoodles/colabrodo', branch = "develop" }
env_logger = "0.10.0"
log = "0.4"
notify = { version = "5.1", default-features = false, features = ["macos_kqueue"] }
russimp = { version = "2.0", features = ["static-link"] }

[dependencies.uuid]
version = "1.3"
features = [
    "v4",                
    "fast-rng",          
    "macro-diagnostics", 
]
